@startuml Car

' + -> public
' - -> private
' # -> protected
' ~ -> package
' underlined -> static (represented by {static} as prefix )

' Define classes
class Car {
    - _brand: string
    - _kilometrage: float
    - _max_speed: float
    - _speed: float
    - _tires: ArrayList<Tire>
    - _is_moving: bool
    - _is_breaking: bool

    + Car(brand: string, max_speed: float, tires: Tire[])
    + kilometrage(): float
    + brand(): string
    + empty_tires(): ArrayList<Tire>
    + set_kilometrage(kilometrage: float): void
    + set_speed(speed: float): void
    + set_breaking(breaking: bool): void
}

' Define classes
class Tire {
    - _psi: float
    - _rec_psi: float
    - _punctured: bool
    + Tire(psi: float, rec_psi: float)
    + get_psi(): float
    + get_rec_psi(): float
    + is_empty(): bool
    + set_psi(psi: float): void
    + is_punctured(): bool
}

' Create composition relationship
Car "1" *--> "4..*" Tire : _tires


@enduml