@startuml Tire

' Define classes
class Tire {
    - _psi: float
    - _rec_psi: float
    - _punctured: bool
    + Tire(psi: float, rec_psi: float)
    + get_psi(): float
    + get_rec_psi(): float
    + is_empty(): bool
    + set_psi(psi: float): void
    + is_punctured(): bool
}

@enduml